AppBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        index:
            type: integer
            column: user_index
        guid:
            type: string
            length: 64
        isActive:
            type: boolean
        balance:
            type: string
            length: 128
        picture:
            type: string
            length: 128
        age:
            type: integer
        eyeColor:
            type: string
            length: 32
        name:
            type: array
        company:
            type: string
            length: 32
        email:
            type: string
            length: 32
        phone:
            type: string
            length: 32
        address:
            type: string
            length: 128
        about:
            type: text
        registered:
            type: string
            length: 32
        latitude:
            type: float
        longitude:
            type: float
        tags:
            type: array
        range:
            type: array
            column: ranges
        friends:
            type: array
        greeting:
            type: string
            length: 64
        favoriteFruit:
            type: string
            length: 32